export const languages = {
  en: {
    code: "en",
    name: "English",
    flag: "🇺🇸",
    translations: {
      // Header
      signIn: "Sign In",
      getStarted: "Get Started",

      // Hero Section
      heroTitle: "Healthcare Reimagined with AI",
      heroSubtitle:
        "Complete healthcare ecosystem with AI disease diagnosis, emergency management, secure doctor consultations, real-time health monitoring, and multi-language support for global accessibility.",
      patientPortal: "Patient Portal",
      doctorPortal: "Doctor Portal",
      emergency: "Emergency",
      emergencyHotline: "24/7 Emergency Hotline",
      emergencyContact: "Call: +1-800-HEALTH-AI | Video Call Available",

      // Stats
      globalPatients: "Global Patients",
      doctorsWorldwide: "Doctors Worldwide",
      aiAccuracy: "AI Accuracy",
      languagesSupported: "Languages",

      // Navigation
      home: "Home",
      features: "Features",
      aiDiagnosis: "AI Diagnosis",
      about: "About",

      // AI Diagnosis
      aiDiagnosisTitle: "Advanced AI Disease Diagnosis",
      aiDiagnosisSubtitle:
        "Real-time analysis using cutting-edge machine learning models for accurate disease detection and health monitoring",
      eyeAnemiaDetection: "Eye Anemia Detection",
      eyeAnemiaDesc: "Real-time analysis using eye/nail images",
      heartDisease: "Heart Disease",
      heartDiseaseDesc: "Cardiovascular risk assessment",
      kidneyStone: "Kidney Stone",
      kidneyStoneDesc: "Early detection and monitoring",
      cancerScreening: "Cancer Screening",
      cancerScreeningDesc: "AI-powered cancer detection",
      asthma: "Asthma",
      asthmaDesc: "Respiratory health monitoring",
      diabetes: "Diabetes",
      diabetesDesc: "Blood sugar level analysis",
      tryAiDiagnosis: "Try AI Diagnosis",

      // Features
      featuresTitle: "Comprehensive Healthcare Ecosystem",
      featuresSubtitle: "Everything you need for modern healthcare management in one secure, intelligent platform",
      doctorPortalTitle: "Doctor Portal",
      patientPortalTitle: "Patient Portal",
      securedVideoMeetings: "Secured Video Meetings",
      securedVideoDesc:
        "End-to-end encrypted consultations with patients and emergency consultations with senior doctors",
      realTimeAnalytics: "Real-time Analytics",
      realTimeAnalyticsDesc: "Track consultations, patient health data visualization, and seamless doctor handoffs",
      ipfsMedicalRecords: "IPFS Medical Records",
      ipfsMedicalRecordsDesc: "Secure, decentralized storage and sharing of patient records using IPFS technology",
      emergencyCorner: "Emergency Corner",
      emergencyCornerDesc: "Priority scheduling, emergency videos, and ambulance booking with real-time tracking",
      aiChatbotOcr: "AI Chatbot & OCR",
      aiChatbotOcrDesc: "Upload medical reports for AI analysis and get suggestions in easy, understandable language",
      healthMonitoring: "Health Monitoring",
      healthMonitoringDesc: "Continuous health tracking with AI alerts for potential health issues",

      // Emergency
      emergencyTitle: "Emergency Management System",
      emergencySubtitle:
        "Immediate assistance when every second counts - AI-powered emergency response and priority care",
      instantConsultation: "Instant Consultation",
      instantConsultationDesc: "Immediate access to emergency doctors and specialists for critical situations",
      emergencyVideos: "Emergency Videos",
      emergencyVideosDesc: "Doctor-created emergency response videos in simple language using NLP",
      smartAmbulance: "Smart Ambulance",
      smartAmbulanceDesc: "Priority-based ambulance scheduling with real-time tracking and ETA",

      // Technology
      technologyTitle: "Cutting-Edge Technology",
      technologySubtitle: "Built with the latest technologies for security, scalability, and global accessibility",
      cryptoAuth: "Crypto Authentication",
      cryptoAuthDesc: "Secure wallet-based authentication",
      ipfsStorage: "IPFS Storage",
      ipfsStorageDesc: "Decentralized file storage",
      aiMlModels: "AI & ML Models",
      aiMlModelsDesc: "Advanced disease diagnosis",
      multiLanguage: "Multi-Language",
      multiLanguageDesc: "Global accessibility",

      // CTA
      ctaTitle: "Ready to Transform Healthcare?",
      ctaSubtitle:
        "Join the global healthcare revolution with AI-powered diagnosis, emergency management, and secure consultations",
      startFreeTrial: "Start Free Trial",
      emergencyAccess: "Emergency Access",

      // Footer
      platform: "Platform",
      emergencyServices: "Emergency Services",
      analyticsDesc: "Analytics Dashboard",
      medicalRecords: "Medical Records",
      telemedicine: "Telemedicine",
      ambulanceBooking: "Ambulance Booking",
      support: "Support",
      helpCenter: "Help Center",
      contactUs: "Contact Us",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      footerTagline:
        "Global healthcare platform powered by AI, providing comprehensive medical services, emergency management, and secure consultations worldwide.",
      rightsReserved: "All rights reserved. Global Healthcare Platform.",
      availableLanguages: "Available in 50+ languages",
      endToEndEncrypted: "End-to-end encrypted",
      emergencySupport: "24/7 Emergency support",
    },
  },
  es: {
    code: "es",
    name: "Español",
    flag: "🇪🇸",
    translations: {
      signIn: "Iniciar Sesión",
      getStarted: "Comenzar",
      heroTitle: "Atención Médica Reimaginada con IA",
      heroSubtitle:
        "Ecosistema completo de atención médica con diagnóstico de enfermedades por IA, gestión de emergencias, consultas médicas seguras, monitoreo de salud en tiempo real y soporte multiidioma para accesibilidad global.",
      patientPortal: "Portal del Paciente",
      doctorPortal: "Portal del Doctor",
      emergency: "Emergencia",
      emergencyHotline: "Línea de Emergencia 24/7",
      emergencyContact: "Llamar: +1-800-HEALTH-AI | Videollamada Disponible",
      globalPatients: "Pacientes Globales",
      doctorsWorldwide: "Doctores en Todo el Mundo",
      aiAccuracy: "Precisión de IA",
      languagesSupported: "Idiomas",
      home: "Inicio",
      features: "Características",
      aiDiagnosis: "Diagnóstico IA",
      about: "Acerca de",
      aiDiagnosisTitle: "Diagnóstico Avanzado de Enfermedades por IA",
      aiDiagnosisSubtitle:
        "Análisis en tiempo real utilizando modelos de aprendizaje automático de vanguardia para detección precisa de enfermedades y monitoreo de salud",
      eyeAnemiaDetection: "Detección de Anemia Ocular",
      eyeAnemiaDesc: "Análisis en tiempo real usando imágenes de ojos/uñas",
      heartDisease: "Enfermedad Cardíaca",
      heartDiseaseDesc: "Evaluación de riesgo cardiovascular",
      kidneyStone: "Cálculo Renal",
      kidneyStoneDesc: "Detección temprana y monitoreo",
      cancerScreening: "Detección de Cáncer",
      cancerScreeningDesc: "Detección de cáncer impulsada por IA",
      asthma: "Asma",
      asthmaDesc: "Monitoreo de salud respiratoria",
      diabetes: "Diabetes",
      diabetesDesc: "Análisis de nivel de azúcar en sangre",
      tryAiDiagnosis: "Probar Diagnóstico IA",
      featuresTitle: "Ecosistema Integral de Atención Médica",
      featuresSubtitle:
        "Todo lo que necesitas para la gestión moderna de atención médica en una plataforma segura e inteligente",
      doctorPortalTitle: "Portal del Doctor",
      patientPortalTitle: "Portal del Paciente",
      securedVideoMeetings: "Reuniones de Video Seguras",
      securedVideoDesc:
        "Consultas cifradas de extremo a extremo con pacientes y consultas de emergencia con médicos senior",
      realTimeAnalytics: "Análisis en Tiempo Real",
      realTimeAnalyticsDesc:
        "Seguimiento de consultas, visualización de datos de salud del paciente y transferencias fluidas de doctores",
      ipfsMedicalRecords: "Registros Médicos IPFS",
      ipfsMedicalRecordsDesc:
        "Almacenamiento y compartición segura y descentralizada de registros de pacientes usando tecnología IPFS",
      emergencyCorner: "Rincón de Emergencia",
      emergencyCornerDesc:
        "Programación prioritaria, videos de emergencia y reserva de ambulancia con seguimiento en tiempo real",
      aiChatbotOcr: "Chatbot IA y OCR",
      aiChatbotOcrDesc:
        "Sube informes médicos para análisis de IA y obtén sugerencias en lenguaje fácil y comprensible",
      healthMonitoring: "Monitoreo de Salud",
      healthMonitoringDesc: "Seguimiento continuo de salud con alertas de IA para posibles problemas de salud",
      emergencyTitle: "Sistema de Gestión de Emergencias",
      emergencySubtitle:
        "Asistencia inmediata cuando cada segundo cuenta - respuesta de emergencia impulsada por IA y atención prioritaria",
      instantConsultation: "Consulta Instantánea",
      instantConsultationDesc: "Acceso inmediato a médicos de emergencia y especialistas para situaciones críticas",
      emergencyVideos: "Videos de Emergencia",
      emergencyVideosDesc: "Videos de respuesta de emergencia creados por doctores en lenguaje simple usando PNL",
      smartAmbulance: "Ambulancia Inteligente",
      smartAmbulanceDesc: "Programación de ambulancia basada en prioridad con seguimiento en tiempo real y ETA",
      technologyTitle: "Tecnología de Vanguardia",
      technologySubtitle: "Construido con las últimas tecnologías para seguridad, escalabilidad y accesibilidad global",
      cryptoAuth: "Autenticación Cripto",
      cryptoAuthDesc: "Autenticación segura basada en billetera",
      ipfsStorage: "Almacenamiento IPFS",
      ipfsStorageDesc: "Almacenamiento de archivos descentralizado",
      aiMlModels: "Modelos IA y ML",
      aiMlModelsDesc: "Diagnóstico avanzado de enfermedades",
      multiLanguage: "Multi-Idioma",
      multiLanguageDesc: "Accesibilidad global",
      ctaTitle: "¿Listo para Transformar la Atención Médica?",
      ctaSubtitle:
        "Únete a la revolución global de atención médica con diagnóstico impulsado por IA, gestión de emergencias y consultas seguras",
      startFreeTrial: "Comenzar Prueba Gratuita",
      emergencyAccess: "Acceso de Emergencia",
      platform: "Plataforma",
      emergencyServices: "Servicios de Emergencia",
      analyticsDesc: "Panel de Análisis",
      medicalRecords: "Registros Médicos",
      telemedicine: "Telemedicina",
      ambulanceBooking: "Reserva de Ambulancia",
      support: "Soporte",
      helpCenter: "Centro de Ayuda",
      contactUs: "Contáctanos",
      privacyPolicy: "Política de Privacidad",
      termsOfService: "Términos de Servicio",
      footerTagline:
        "Plataforma global de atención médica impulsada por IA, proporcionando servicios médicos integrales, gestión de emergencias y consultas seguras en todo el mundo.",
      rightsReserved: "Todos los derechos reservados. Plataforma Global de Atención Médica.",
      availableLanguages: "Disponible en más de 50 idiomas",
      endToEndEncrypted: "Cifrado de extremo a extremo",
      emergencySupport: "Soporte de emergencia 24/7",
    },
  },
  fr: {
    code: "fr",
    name: "Français",
    flag: "🇫🇷",
    translations: {
      signIn: "Se Connecter",
      getStarted: "Commencer",
      heroTitle: "Soins de Santé Réinventés avec l'IA",
      heroSubtitle:
        "Écosystème complet de soins de santé avec diagnostic de maladies par IA, gestion d'urgence, consultations médicales sécurisées, surveillance de santé en temps réel et support multilingue pour l'accessibilité mondiale.",
      patientPortal: "Portail Patient",
      doctorPortal: "Portail Médecin",
      emergency: "Urgence",
      emergencyHotline: "Ligne d'Urgence 24/7",
      emergencyContact: "Appeler: +1-800-HEALTH-AI | Appel Vidéo Disponible",
      globalPatients: "Patients Mondiaux",
      doctorsWorldwide: "Médecins dans le Monde",
      aiAccuracy: "Précision IA",
      languagesSupported: "Langues",
      home: "Accueil",
      features: "Fonctionnalités",
      aiDiagnosis: "Diagnostic IA",
      about: "À Propos",
      aiDiagnosisTitle: "Diagnostic Avancé de Maladies par IA",
      aiDiagnosisSubtitle:
        "Analyse en temps réel utilisant des modèles d'apprentissage automatique de pointe pour une détection précise des maladies et une surveillance de la santé",
      eyeAnemiaDetection: "Détection d'Anémie Oculaire",
      eyeAnemiaDesc: "Analyse en temps réel utilisant des images d'yeux/ongles",
      heartDisease: "Maladie Cardiaque",
      heartDiseaseDesc: "Évaluation du risque cardiovasculaire",
      kidneyStone: "Calcul Rénal",
      kidneyStoneDesc: "Détection précoce et surveillance",
      cancerScreening: "Dépistage du Cancer",
      cancerScreeningDesc: "Détection du cancer alimentée par l'IA",
      asthma: "Asthme",
      asthmaDesc: "Surveillance de la santé respiratoire",
      diabetes: "Diabète",
      diabetesDesc: "Analyse du niveau de sucre dans le sang",
      tryAiDiagnosis: "Essayer le Diagnostic IA",
      featuresTitle: "Écosystème Complet de Soins de Santé",
      featuresSubtitle:
        "Tout ce dont vous avez besoin pour la gestion moderne des soins de santé dans une plateforme sécurisée et intelligente",
      doctorPortalTitle: "Portail Médecin",
      patientPortalTitle: "Portail Patient",
      securedVideoMeetings: "Réunions Vidéo Sécurisées",
      securedVideoDesc:
        "Consultations chiffrées de bout en bout avec les patients et consultations d'urgence avec des médecins seniors",
      realTimeAnalytics: "Analyses en Temps Réel",
      realTimeAnalyticsDesc:
        "Suivi des consultations, visualisation des données de santé des patients et transferts fluides de médecins",
      ipfsMedicalRecords: "Dossiers Médicaux IPFS",
      ipfsMedicalRecordsDesc:
        "Stockage et partage sécurisés et décentralisés des dossiers patients utilisant la technologie IPFS",
      emergencyCorner: "Coin d'Urgence",
      emergencyCornerDesc:
        "Planification prioritaire, vidéos d'urgence et réservation d'ambulance avec suivi en temps réel",
      aiChatbotOcr: "Chatbot IA et OCR",
      aiChatbotOcrDesc:
        "Téléchargez des rapports médicaux pour l'analyse IA et obtenez des suggestions dans un langage facile et compréhensible",
      healthMonitoring: "Surveillance de la Santé",
      healthMonitoringDesc: "Suivi continu de la santé avec des alertes IA pour les problèmes de santé potentiels",
      emergencyTitle: "Système de Gestion d'Urgence",
      emergencySubtitle:
        "Assistance immédiate quand chaque seconde compte - réponse d'urgence alimentée par l'IA et soins prioritaires",
      instantConsultation: "Consultation Instantanée",
      instantConsultationDesc: "Accès immédiat aux médecins d'urgence et spécialistes pour les situations critiques",
      emergencyVideos: "Vidéos d'Urgence",
      emergencyVideosDesc:
        "Vidéos de réponse d'urgence créées par des médecins dans un langage simple utilisant le NLP",
      smartAmbulance: "Ambulance Intelligente",
      smartAmbulanceDesc: "Planification d'ambulance basée sur la priorité avec suivi en temps réel et ETA",
      technologyTitle: "Technologie de Pointe",
      technologySubtitle:
        "Construit avec les dernières technologies pour la sécurité, l'évolutivité et l'accessibilité mondiale",
      cryptoAuth: "Authentification Crypto",
      cryptoAuthDesc: "Authentification sécurisée basée sur le portefeuille",
      ipfsStorage: "Stockage IPFS",
      ipfsStorageDesc: "Stockage de fichiers décentralisé",
      aiMlModels: "Modèles IA et ML",
      aiMlModelsDesc: "Diagnostic avancé de maladies",
      multiLanguage: "Multi-Langue",
      multiLanguageDesc: "Accessibilité mondiale",
      ctaTitle: "Prêt à Transformer les Soins de Santé?",
      ctaSubtitle:
        "Rejoignez la révolution mondiale des soins de santé avec diagnostic alimenté par l'IA, gestion d'urgence et consultations sécurisées",
      startFreeTrial: "Commencer l'Essai Gratuit",
      emergencyAccess: "Accès d'Urgence",
      platform: "Plateforme",
      emergencyServices: "Services d'Urgence",
      analyticsDesc: "Tableau de Bord d'Analyse",
      medicalRecords: "Dossiers Médicaux",
      telemedicine: "Télémédecine",
      ambulanceBooking: "Réservation d'Ambulance",
      support: "Support",
      helpCenter: "Centre d'Aide",
      contactUs: "Nous Contacter",
      privacyPolicy: "Politique de Confidentialité",
      termsOfService: "Conditions de Service",
      footerTagline:
        "Plateforme mondiale de soins de santé alimentée par l'IA, fournissant des services médicaux complets, la gestion d'urgence et des consultations sécurisées dans le monde entier.",
      rightsReserved: "Tous droits réservés. Plateforme Mondiale de Soins de Santé.",
      availableLanguages: "Disponible en plus de 50 langues",
      endToEndEncrypted: "Chiffré de bout en bout",
      emergencySupport: "Support d'urgence 24/7",
    },
  },
  hi: {
    code: "hi",
    name: "हिंदी",
    flag: "🇮🇳",
    translations: {
      signIn: "साइन इन करें",
      getStarted: "शुरू करें",
      heroTitle: "AI के साथ स्वास्थ्य सेवा की नई कल्पना",
      heroSubtitle:
        "AI रोग निदान, आपातकालीन प्रबंधन, सुरक्षित डॉक्टर परामर्श, रीयल-टाइम स्वास्थ्य निगरानी, और वैश्विक पहुंच के लिए बहुभाषी समर्थन के साथ पूर्ण स्वास्थ्य सेवा पारिस्थितिकी तंत्र।",
      patientPortal: "रोगी पोर्टल",
      doctorPortal: "डॉक्टर पोर्टल",
      emergency: "आपातकाल",
      emergencyHotline: "24/7 आपातकालीन हॉटलाइन",
      emergencyContact: "कॉल करें: +1-800-HEALTH-AI | वीडियो कॉल उपलब्ध",
      globalPatients: "वैश्विक रोगी",
      doctorsWorldwide: "विश्वव्यापी डॉक्टर",
      aiAccuracy: "AI सटीकता",
      languagesSupported: "भाषाएं",
      home: "होम",
      features: "विशेषताएं",
      aiDiagnosis: "AI निदान",
      about: "के बारे में",
      aiDiagnosisTitle: "उन्नत AI रोग निदान",
      aiDiagnosisSubtitle:
        "सटीक रोग का पता लगाने और स्वास्थ्य निगरानी के लिए अत्याधुनिक मशीन लर्निंग मॉडल का उपयोग करके रीयल-टाइम विश्लेषण",
      eyeAnemiaDetection: "आंख एनीमिया का पता लगाना",
      eyeAnemiaDesc: "आंख/नाखून की छवियों का उपयोग करके रीयल-टाइम विश्लेषण",
      heartDisease: "हृदय रोग",
      heartDiseaseDesc: "हृदय संबंधी जोखिम मूल्यांकन",
      kidneyStone: "गुर्दे की पथरी",
      kidneyStoneDesc: "प्रारंभिक पहचान और निगरानी",
      cancerScreening: "कैंसर स्क्रीनिंग",
      cancerScreeningDesc: "AI-संचालित कैंसर का पता लगाना",
      asthma: "दमा",
      asthmaDesc: "श्वसन स्वास्थ्य निगरानी",
      diabetes: "मधुमेह",
      diabetesDesc: "रक्त शर्करा स्तर विश्लेषण",
      tryAiDiagnosis: "AI निदान आज़माएं",
      featuresTitle: "व्यापक स्वास्थ्य सेवा पारिस्थितिकी तंत्र",
      featuresSubtitle: "एक सुरक्षित, बुद्धिमान प्लेटफॉर्म में आधुनिक स्वास्थ्य सेवा प्रबंधन के लिए आपको जो कुछ भी चाहिए",
      doctorPortalTitle: "डॉक्टर पोर्टल",
      patientPortalTitle: "रोगी पोर्टल",
      securedVideoMeetings: "सुरक्षित वीडियो मीटिंग",
      securedVideoDesc: "रोगियों के साथ एंड-टू-एंड एन्क्रिप्टेड परामर्श और वरिष्ठ डॉक्टरों के साथ आपातकालीन परामर्श",
      realTimeAnalytics: "रीयल-टाइम एनालिटिक्स",
      realTimeAnalyticsDesc: "परामर्श ट्रैकिंग, रोगी स्वास्थ्य डेटा विज़ुअलाइज़ेशन, और निर्बाध डॉक्टर हैंडऑफ़",
      ipfsMedicalRecords: "IPFS मेडिकल रिकॉर्ड",
      ipfsMedicalRecordsDesc: "IPFS तकनीक का उपयोग करके रोगी रिकॉर्ड का सुरक्षित, विकेंद्रीकृत भंडारण और साझाकरण",
      emergencyCorner: "आपातकालीन कॉर्नर",
      emergencyCornerDesc: "प्राथमिकता शेड्यूलिंग, आपातकालीन वीडियो, और रीयल-टाइम ट्रैकिंग के साथ एम्बुलेंस बुकिंग",
      aiChatbotOcr: "AI चैटबॉट और OCR",
      aiChatbotOcrDesc: "AI विश्लेषण के लिए मेडिकल रिपोर्ट अपलोड करें और आसान, समझने योग्य भाषा में सुझाव प्राप्त करें",
      healthMonitoring: "स्वास्थ्य निगरानी",
      healthMonitoringDesc: "संभावित स्वास्थ्य समस्याओं के लिए AI अलर्ट के साथ निरंतर स्वास्थ्य ट्रैकिंग",
      emergencyTitle: "आपातकालीन प्रबंधन प्रणाली",
      emergencySubtitle: "जब हर सेकंड मायने रखता है तो तत्काल सहायता - AI-संचालित आपातकालीन प्रतिक्रिया और प्राथमिकता देखभाल",
      instantConsultation: "तत्काल परामर्श",
      instantConsultationDesc: "गंभीर स्थितियों के लिए आपातकालीन डॉक्टरों और विशेषज्ञों तक तत्काल पहुंच",
      emergencyVideos: "आपातकालीन वीडियो",
      emergencyVideosDesc: "NLP का उपयोग करके सरल भाषा में डॉक्टर-निर्मित आपातकालीन प्रतिक्रिया वीडियो",
      smartAmbulance: "स्मार्ट एम्बुलेंस",
      smartAmbulanceDesc: "रीयल-टाइम ट्रैकिंग और ETA के साथ प्राथमिकता-आधारित एम्बुलेंस शेड्यूलिंग",
      technologyTitle: "अत्याधुनिक तकनीक",
      technologySubtitle: "सुरक्षा, स्केलेबिलिटी और वैश्विक पहुंच के लिए नवीनतम तकनीकों के साथ निर्मित",
      cryptoAuth: "क्रिप्टो प्रमाणीकरण",
      cryptoAuthDesc: "सुरक्षित वॉलेट-आधारित प्रमाणीकरण",
      ipfsStorage: "IPFS स्टोरेज",
      ipfsStorageDesc: "विकेंद्रीकृत फ़ाइल स्टोरेज",
      aiMlModels: "AI और ML मॉडल",
      aiMlModelsDesc: "उन्नत रोग निदान",
      multiLanguage: "बहुभाषी",
      multiLanguageDesc: "वैश्विक पहुंच",
      ctaTitle: "स्वास्थ्य सेवा को बदलने के लिए तैयार हैं?",
      ctaSubtitle: "AI-संचालित निदान, आपातकालीन प्रबंधन, और सुरक्षित परामर्श के साथ वैश्विक स्वास्थ्य सेवा क्रांति में शामिल हों",
      startFreeTrial: "मुफ्त परीक्षण शुरू करें",
      emergencyAccess: "आपातकालीन पहुंच",
      platform: "प्लेटफॉर्म",
      emergencyServices: "आपातकालीन सेवाएं",
      analyticsDesc: "एनालिटिक्स डैशबोर्ड",
      medicalRecords: "मेडिकल रिकॉर्ड",
      telemedicine: "टेलीमेडिसिन",
      ambulanceBooking: "एम्बुलेंस बुकिंग",
      support: "सहायता",
      helpCenter: "सहायता केंद्र",
      contactUs: "संपर्क करें",
      privacyPolicy: "गोपनीयता नीति",
      termsOfService: "सेवा की शर्तें",
      footerTagline:
        "AI द्वारा संचालित वैश्विक स्वास्थ्य सेवा प्लेटफॉर्म, दुनिया भर में व्यापक चिकित्सा सेवाएं, आपातकालीन प्रबंधन, और सुरक्षित परामर्श प्रदान करता है।",
      rightsReserved: "सभी अधिकार सुरक्षित। वैश्विक स्वास्थ्य सेवा प्लेटफॉर्म।",
      availableLanguages: "50+ भाषाओं में उपलब्ध",
      endToEndEncrypted: "एंड-टू-एंड एन्क्रिप्टेड",
      emergencySupport: "24/7 आपातकालीन सहायता",
    },
  },
  zh: {
    code: "zh",
    name: "中文",
    flag: "🇨🇳",
    translations: {
      signIn: "登录",
      getStarted: "开始使用",
      heroTitle: "AI重新定义医疗保健",
      heroSubtitle:
        "完整的医疗保健生态系统，包含AI疾病诊断、紧急管理、安全医生咨询、实时健康监测和多语言支持，实现全球可访问性。",
      patientPortal: "患者门户",
      doctorPortal: "医生门户",
      emergency: "紧急情况",
      emergencyHotline: "24/7紧急热线",
      emergencyContact: "致电：+1-800-HEALTH-AI | 视频通话可用",
      globalPatients: "全球患者",
      doctorsWorldwide: "全球医生",
      aiAccuracy: "AI准确率",
      languagesSupported: "语言",
      home: "首页",
      features: "功能",
      aiDiagnosis: "AI诊断",
      about: "关于",
      aiDiagnosisTitle: "先进的AI疾病诊断",
      aiDiagnosisSubtitle: "使用尖端机器学习模型进行实时分析，准确检测疾病和健康监测",
      eyeAnemiaDetection: "眼部贫血检测",
      eyeAnemiaDesc: "使用眼部/指甲图像进行实时分析",
      heartDisease: "心脏病",
      heartDiseaseDesc: "心血管风险评估",
      kidneyStone: "肾结石",
      kidneyStoneDesc: "早期检测和监测",
      cancerScreening: "癌症筛查",
      cancerScreeningDesc: "AI驱动的癌症检测",
      asthma: "哮喘",
      asthmaDesc: "呼吸健康监测",
      diabetes: "糖尿病",
      diabetesDesc: "血糖水平分析",
      tryAiDiagnosis: "尝试AI诊断",
      featuresTitle: "综合医疗保健生态系统",
      featuresSubtitle: "在一个安全、智能的平台中，您需要的现代医疗保健管理的一切",
      doctorPortalTitle: "医生门户",
      patientPortalTitle: "患者门户",
      securedVideoMeetings: "安全视频会议",
      securedVideoDesc: "与患者进行端到端加密咨询，与资深医生进行紧急咨询",
      realTimeAnalytics: "实时分析",
      realTimeAnalyticsDesc: "跟踪咨询、患者健康数据可视化和无缝医生交接",
      ipfsMedicalRecords: "IPFS医疗记录",
      ipfsMedicalRecordsDesc: "使用IPFS技术安全、去中心化地存储和共享患者记录",
      emergencyCorner: "紧急角落",
      emergencyCornerDesc: "优先调度、紧急视频和实时跟踪的救护车预订",
      aiChatbotOcr: "AI聊天机器人和OCR",
      aiChatbotOcrDesc: "上传医疗报告进行AI分析，获得易于理解的语言建议",
      healthMonitoring: "健康监测",
      healthMonitoringDesc: "持续健康跟踪，AI警报潜在健康问题",
      emergencyTitle: "紧急管理系统",
      emergencySubtitle: "当每一秒都很重要时的即时援助 - AI驱动的紧急响应和优先护理",
      instantConsultation: "即时咨询",
      instantConsultationDesc: "在危急情况下立即接触紧急医生和专家",
      emergencyVideos: "紧急视频",
      emergencyVideosDesc: "使用NLP的医生创建的简单语言紧急响应视频",
      smartAmbulance: "智能救护车",
      smartAmbulanceDesc: "基于优先级的救护车调度，实时跟踪和ETA",
      technologyTitle: "尖端技术",
      technologySubtitle: "采用最新技术构建，确保安全性、可扩展性和全球可访问性",
      cryptoAuth: "加密认证",
      cryptoAuthDesc: "基于钱包的安全认证",
      ipfsStorage: "IPFS存储",
      ipfsStorageDesc: "去中心化文件存储",
      aiMlModels: "AI和ML模型",
      aiMlModelsDesc: "先进疾病诊断",
      multiLanguage: "多语言",
      multiLanguageDesc: "全球可访问性",
      ctaTitle: "准备好改变医疗保健了吗？",
      ctaSubtitle: "加入全球医疗保健革命，享受AI驱动的诊断、紧急管理和安全咨询",
      startFreeTrial: "开始免费试用",
      emergencyAccess: "紧急访问",
      platform: "平台",
      emergencyServices: "紧急服务",
      analyticsDesc: "分析仪表板",
      medicalRecords: "医疗记录",
      telemedicine: "远程医疗",
      ambulanceBooking: "救护车预订",
      support: "支持",
      helpCenter: "帮助中心",
      contactUs: "联系我们",
      privacyPolicy: "隐私政策",
      termsOfService: "服务条款",
      footerTagline: "AI驱动的全球医疗保健平台，在全球范围内提供全面的医疗服务、紧急管理和安全咨询。",
      rightsReserved: "版权所有。全球医疗保健平台。",
      availableLanguages: "支持50+种语言",
      endToEndEncrypted: "端到端加密",
      emergencySupport: "24/7紧急支持",
    },
  },
  ar: {
    code: "ar",
    name: "العربية",
    flag: "🇸🇦",
    translations: {
      signIn: "تسجيل الدخول",
      getStarted: "ابدأ الآن",
      heroTitle: "الرعاية الصحية المعاد تصورها بالذكاء الاصطناعي",
      heroSubtitle:
        "نظام بيئي شامل للرعاية الصحية مع تشخيص الأمراض بالذكاء الاصطناعي، وإدارة الطوارئ، والاستشارات الطبية الآمنة، ومراقبة الصحة في الوقت الفعلي، والدعم متعدد اللغات لإمكانية الوصول العالمية.",
      patientPortal: "بوابة المريض",
      doctorPortal: "بوابة الطبيب",
      emergency: "طوارئ",
      emergencyHotline: "خط الطوارئ 24/7",
      emergencyContact: "اتصل: +1-800-HEALTH-AI | مكالمة فيديو متاحة",
      globalPatients: "المرضى العالميون",
      doctorsWorldwide: "الأطباء حول العالم",
      aiAccuracy: "دقة الذكاء الاصطناعي",
      languagesSupported: "اللغات",
      home: "الرئيسية",
      features: "الميزات",
      aiDiagnosis: "تشخيص الذكاء الاصطناعي",
      about: "حول",
      aiDiagnosisTitle: "تشخيص متقدم للأمراض بالذكاء الاصطناعي",
      aiDiagnosisSubtitle:
        "تحليل في الوقت الفعلي باستخدام نماذج التعلم الآلي المتطورة للكشف الدقيق عن الأمراض ومراقبة الصحة",
      eyeAnemiaDetection: "كشف فقر الدم بالعين",
      eyeAnemiaDesc: "تحليل في الوقت الفعلي باستخدام صور العين/الأظافر",
      heartDisease: "أمراض القلب",
      heartDiseaseDesc: "تقييم مخاطر القلب والأوعية الدموية",
      kidneyStone: "حصى الكلى",
      kidneyStoneDesc: "الكشف المبكر والمراقبة",
      cancerScreening: "فحص السرطان",
      cancerScreeningDesc: "كشف السرطان بالذكاء الاصطناعي",
      asthma: "الربو",
      asthmaDesc: "مراقبة صحة الجهاز التنفسي",
      diabetes: "السكري",
      diabetesDesc: "تحليل مستوى السكر في الدم",
      tryAiDiagnosis: "جرب تشخيص الذكاء الاصطناعي",
      featuresTitle: "نظام بيئي شامل للرعاية الصحية",
      featuresSubtitle: "كل ما تحتاجه لإدارة الرعاية الصحية الحديثة في منصة آمنة وذكية",
      doctorPortalTitle: "بوابة الطبيب",
      patientPortalTitle: "بوابة المريض",
      securedVideoMeetings: "اجتماعات فيديو آمنة",
      securedVideoDesc: "استشارات مشفرة من طرف إلى طرف مع المرضى واستشارات طوارئ مع الأطباء الكبار",
      realTimeAnalytics: "تحليلات في الوقت الفعلي",
      realTimeAnalyticsDesc: "تتبع الاستشارات، وتصور بيانات صحة المريض، وتسليم الأطباء السلس",
      ipfsMedicalRecords: "السجلات الطبية IPFS",
      ipfsMedicalRecordsDesc: "تخزين ومشاركة آمنة ولامركزية لسجلات المرضى باستخدام تقنية IPFS",
      emergencyCorner: "ركن الطوارئ",
      emergencyCornerDesc: "جدولة أولوية، وفيديوهات طوارئ، وحجز سيارة إسعاف مع تتبع في الوقت الفعلي",
      aiChatbotOcr: "روبوت دردشة ذكي و OCR",
      aiChatbotOcrDesc: "ارفع التقارير الطبية لتحليل الذكاء الاصطناعي واحصل على اقتراحات بلغة سهلة ومفهومة",
      healthMonitoring: "مراقبة الصحة",
      healthMonitoringDesc: "تتبع صحي مستمر مع تنبيهات الذكاء الاصطناعي للمشاكل الصحية المحتملة",
      emergencyTitle: "نظام إدارة الطوارئ",
      emergencySubtitle: "مساعدة فورية عندما تكون كل ثانية مهمة - استجابة طوارئ بالذكاء الاصطناعي ورعاية أولوية",
      instantConsultation: "استشارة فورية",
      instantConsultationDesc: "وصول فوري لأطباء الطوارئ والمتخصصين للحالات الحرجة",
      emergencyVideos: "فيديوهات الطوارئ",
      emergencyVideosDesc: "فيديوهات استجابة طوارئ من إنشاء الأطباء بلغة بسيطة باستخدام معالجة اللغة الطبيعية",
      smartAmbulance: "سيارة إسعاف ذكية",
      smartAmbulanceDesc: "جدولة سيارة إسعاف قائمة على الأولوية مع تتبع في الوقت الفعلي ووقت الوصول المقدر",
      technologyTitle: "تقنية متطورة",
      technologySubtitle: "مبني بأحدث التقنيات للأمان وقابلية التوسع وإمكانية الوصول العالمية",
      cryptoAuth: "مصادقة التشفير",
      cryptoAuthDesc: "مصادقة آمنة قائمة على المحفظة",
      ipfsStorage: "تخزين IPFS",
      ipfsStorageDesc: "تخزين ملفات لامركزي",
      aiMlModels: "نماذج الذكاء الاصطناعي والتعلم الآلي",
      aiMlModelsDesc: "تشخيص متقدم للأمراض",
      multiLanguage: "متعدد اللغات",
      multiLanguageDesc: "إمكانية الوصول العالمية",
      ctaTitle: "مستعد لتحويل الرعاية الصحية؟",
      ctaSubtitle:
        "انضم إلى ثورة الرعاية الصحية العالمية مع التشخيص بالذكاء الاصطناعي وإدارة الطوارئ والاستشارات الآمنة",
      startFreeTrial: "ابدأ التجربة المجانية",
      emergencyAccess: "وصول الطوارئ",
      platform: "المنصة",
      emergencyServices: "خدمات الطوارئ",
      analyticsDesc: "لوحة التحليلات",
      medicalRecords: "السجلات الطبية",
      telemedicine: "الطب عن بُعد",
      ambulanceBooking: "حجز سيارة الإسعاف",
      support: "الدعم",
      helpCenter: "مركز المساعدة",
      contactUs: "اتصل بنا",
      privacyPolicy: "سياسة الخصوصية",
      termsOfService: "شروط الخدمة",
      footerTagline:
        "منصة رعاية صحية عالمية مدعومة بالذكاء الاصطناعي، تقدم خدمات طبية شاملة وإدارة طوارئ واستشارات آمنة في جميع أنحاء العالم.",
      rightsReserved: "جميع الحقوق محفوظة. منصة الرعاية الصحية العالمية.",
      availableLanguages: "متاح بأكثر من 50 لغة",
      endToEndEncrypted: "مشفر من طرف إلى طرف",
      emergencySupport: "دعم طوارئ 24/7",
    },
  },
  de: {
    code: "de",
    name: "Deutsch",
    flag: "🇩🇪",
    translations: {
      signIn: "Anmelden",
      getStarted: "Loslegen",
      heroTitle: "Gesundheitswesen neu erfunden mit KI",
      heroSubtitle:
        "Vollständiges Gesundheitsökosystem mit KI-Krankheitsdiagnose, Notfallmanagement, sicheren Arztberatungen, Echtzeit-Gesundheitsüberwachung und mehrsprachiger Unterstützung für globale Zugänglichkeit.",
      patientPortal: "Patientenportal",
      doctorPortal: "Arztportal",
      emergency: "Notfall",
      emergencyHotline: "24/7 Notfall-Hotline",
      emergencyContact: "Anrufen: +1-800-HEALTH-AI | Videoanruf verfügbar",
      globalPatients: "Globale Patienten",
      doctorsWorldwide: "Ärzte weltweit",
      aiAccuracy: "KI-Genauigkeit",
      languagesSupported: "Sprachen",
      home: "Startseite",
      features: "Funktionen",
      aiDiagnosis: "KI-Diagnose",
      about: "Über uns",
      aiDiagnosisTitle: "Fortgeschrittene KI-Krankheitsdiagnose",
      aiDiagnosisSubtitle:
        "Echtzeitanalyse mit modernsten Machine-Learning-Modellen für präzise Krankheitserkennung und Gesundheitsüberwachung",
      eyeAnemiaDetection: "Augen-Anämie-Erkennung",
      eyeAnemiaDesc: "Echtzeitanalyse mit Augen-/Nagelbildern",
      heartDisease: "Herzkrankheit",
      heartDiseaseDesc: "Herz-Kreislauf-Risikobewertung",
      kidneyStone: "Nierenstein",
      kidneyStoneDesc: "Früherkennung und Überwachung",
      cancerScreening: "Krebsvorsorge",
      cancerScreeningDesc: "KI-gestützte Krebserkennung",
      asthma: "Asthma",
      asthmaDesc: "Atemwegsgesundheitsüberwachung",
      diabetes: "Diabetes",
      diabetesDesc: "Blutzuckerspiegel-Analyse",
      tryAiDiagnosis: "KI-Diagnose ausprobieren",
      featuresTitle: "Umfassendes Gesundheitsökosystem",
      featuresSubtitle:
        "Alles was Sie für modernes Gesundheitsmanagement in einer sicheren, intelligenten Plattform benötigen",
      doctorPortalTitle: "Arztportal",
      patientPortalTitle: "Patientenportal",
      securedVideoMeetings: "Sichere Videobesprechungen",
      securedVideoDesc:
        "Ende-zu-Ende verschlüsselte Beratungen mit Patienten und Notfallberatungen mit erfahrenen Ärzten",
      realTimeAnalytics: "Echtzeit-Analytik",
      realTimeAnalyticsDesc:
        "Verfolgung von Beratungen, Visualisierung von Patientengesundheitsdaten und nahtlose Arztübergaben",
      ipfsMedicalRecords: "IPFS-Krankenakten",
      ipfsMedicalRecordsDesc: "Sichere, dezentrale Speicherung und Freigabe von Patientenakten mit IPFS-Technologie",
      emergencyCorner: "Notfall-Ecke",
      emergencyCornerDesc: "Prioritätsplanung, Notfallvideos und Krankenwagenbuchung mit Echtzeit-Verfolgung",
      aiChatbotOcr: "KI-Chatbot & OCR",
      aiChatbotOcrDesc:
        "Laden Sie medizinische Berichte für KI-Analyse hoch und erhalten Sie Vorschläge in einfacher, verständlicher Sprache",
      healthMonitoring: "Gesundheitsüberwachung",
      healthMonitoringDesc:
        "Kontinuierliche Gesundheitsverfolgung mit KI-Warnungen für potenzielle Gesundheitsprobleme",
      emergencyTitle: "Notfallmanagementsystem",
      emergencySubtitle:
        "Sofortige Hilfe, wenn jede Sekunde zählt - KI-gestützte Notfallreaktion und Prioritätsversorgung",
      instantConsultation: "Sofortberatung",
      instantConsultationDesc: "Sofortiger Zugang zu Notärzten und Spezialisten für kritische Situationen",
      emergencyVideos: "Notfallvideos",
      emergencyVideosDesc: "Von Ärzten erstellte Notfallreaktionsvideos in einfacher Sprache mit NLP",
      smartAmbulance: "Intelligenter Krankenwagen",
      smartAmbulanceDesc: "Prioritätsbasierte Krankenwagenplanung mit Echtzeit-Verfolgung und ETA",
      technologyTitle: "Modernste Technologie",
      technologySubtitle:
        "Gebaut mit den neuesten Technologien für Sicherheit, Skalierbarkeit und globale Zugänglichkeit",
      cryptoAuth: "Krypto-Authentifizierung",
      cryptoAuthDesc: "Sichere wallet-basierte Authentifizierung",
      ipfsStorage: "IPFS-Speicher",
      ipfsStorageDesc: "Dezentrale Dateispeicherung",
      aiMlModels: "KI & ML-Modelle",
      aiMlModelsDesc: "Fortgeschrittene Krankheitsdiagnose",
      multiLanguage: "Mehrsprachig",
      multiLanguageDesc: "Globale Zugänglichkeit",
      ctaTitle: "Bereit, das Gesundheitswesen zu transformieren?",
      ctaSubtitle:
        "Treten Sie der globalen Gesundheitsrevolution bei mit KI-gestützter Diagnose, Notfallmanagement und sicheren Beratungen",
      startFreeTrial: "Kostenlose Testversion starten",
      emergencyAccess: "Notfallzugang",
      platform: "Plattform",
      emergencyServices: "Notfalldienste",
      analyticsDesc: "Analyse-Dashboard",
      medicalRecords: "Krankenakten",
      telemedicine: "Telemedizin",
      ambulanceBooking: "Krankenwagenbuchung",
      support: "Support",
      helpCenter: "Hilfezentrum",
      contactUs: "Kontaktieren Sie uns",
      privacyPolicy: "Datenschutzrichtlinie",
      termsOfService: "Nutzungsbedingungen",
      footerTagline:
        "Globale Gesundheitsplattform powered by KI, die umfassende medizinische Dienstleistungen, Notfallmanagement und sichere Beratungen weltweit bietet.",
      rightsReserved: "Alle Rechte vorbehalten. Globale Gesundheitsplattform.",
      availableLanguages: "Verfügbar in 50+ Sprachen",
      endToEndEncrypted: "Ende-zu-Ende verschlüsselt",
      emergencySupport: "24/7 Notfallsupport",
    },
  },
}

export const getLanguageList = () => {
  return Object.values(languages).map((lang) => ({
    code: lang.code,
    name: lang.name,
    flag: lang.flag,
  }))
}

export const getTranslations = (languageCode: string) => {
  return languages[languageCode as keyof typeof languages]?.translations || languages.en.translations
}
